{
 "title": "Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage by Pods",
   "type": "timeseries",
   "description": "memory usage by pods in MiB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(container_memory_usage_bytes{namespace=\"default\"}[5m])/1024/1024) by (container)"
    }
   ]
  },
  {
   "title": "CPU Usage by Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum ( rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m]))  by (container)"
    }
   ]
  },
  {
   "title": "Disk I/O Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"default\"}[5m])/1024/1024) by (container, device)\n"
    }
   ]
  },
  {
   "title": "Disk I/O Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"default\"}[5m])/1024/1024) by (container, device)"
    }
   ]
  },
  {
   "title": "Network Transmit by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\"}[5m])/1024/1024) by (pod)"
    }
   ]
  },
  {
   "title": "Network Receive by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"default\"}[5m])/1024/1024) by (pod)"
    }
   ]
  },
  {
   "title": "spark-worker-1 CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"my-release-spark-worker-1\"}[1m]))",
     "legendFormat": "spark-worker-1"
    }
   ]
  },
  {
   "title": "spark-worker-0 CPU Usage",
   "type": "gauge",
   "description": "spark-worker CPU usage ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"my-release-spark-worker-0\"}[1m]))",
     "legendFormat": "spark-worker-0"
    }
   ]
  },
  {
   "title": "Network Transmit Error ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"default\"}[5m])/1024/1024) by (pod)"
    }
   ]
  },
  {
   "title": "Network Receive Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"default\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "spark-master CPU Usage",
   "type": "gauge",
   "description": "spark-master cpu usage by",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=\"my-release-spark-master-0\"}[1m])",
     "legendFormat": "spark-master"
    }
   ]
  }
 ]
}