{
 "title": "DB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Postgresql Memory Usage ",
   "type": "timeseries",
   "description": "postgresql memory usage in MiB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{container=\"postgresql\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Postgresql CPU USAGE",
   "type": "timeseries",
   "description": "cpu usage of postgresql",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{pod=\"postgresql-0\"}[5m])) by (container)"
    }
   ]
  },
  {
   "title": "Woundcare DB Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"woundcaredb\"}"
    }
   ]
  },
  {
   "title": "Woundcare DB Usage",
   "type": "gauge",
   "description": "usage of woundcare database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_database_size_bytes{datname=\"woundcaredb\"})/1024/1024"
    }
   ]
  },
  {
   "title": "UP PG INSTANCES",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up" }
   ]
  },
  {
   "title": "Max Active Transaction by DB",
   "type": "timeseries",
   "description": "the slowest active transaction",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration"
    }
   ]
  }
 ]
}